### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Abhineet0011**
Changed spelling mistakes

### CODE REVIEW

**Comment by xandora** [comment]
The first edit is fine, although there should not be a space between `'The Odin Project'` and the full stop.

The second change does not make sense. Why put a comma after `so`? There is not a natural pause there when reading that sentence.

**Comment by xandora** [comment]
Whoops, wrong button... Where's the request change button gone?! Anyway, if you adjust the PR we can accept it.

**Comment by marvingay** [comment]
I made additional revisions to the README so it reads a tad bit better.

@Abhineet0011  Thank you for your contribution.

**Review by xandora — COMMENTED** [review]
looks good.

**Pull request merged**
