### PR TITLE
10_fibonacci: Add alternative solution in fibonacci-solution.js

### PR DESCRIPTION
**Pull request by Luislev**
## Because

Students get to learn an alternative way to solve the fibonacci problem using an array with 2 values, especially for the ones who are currently in fundamentals part 5 learning about arrays.

## This PR

- Add fib array containing the value 0 and 1.
- Abbreviate fibonacci calculation in for loop.
- return fibonacci count.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01_helloWorld: Update test cases`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If this PR includes any changes that affect the solution of an exercise, I've also updated the solution in the `/solutions` folder

### CODE REVIEW

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript 

Can someone take a look and decide if the proposed solution is preferable to what is already there.

**Comment by thatblindgeye** [comment]
Personally I still feel like having this sort of solution be a commented out, alternative (similar to what was done in a previous PR: https://github.com/TheOdinProject/javascript-exercises/pull/270/files#diff-343d59eebe790052715d0996cdf046b64da2c19fd913704f9b3f51bea7c1ebde) is better. If others prefer this proposed way, though, I wouldn't block it

**Comment by Luislev** [comment]
> Personally I still feel like having this sort of solution be a commented out, alternative (similar to what was done in a previous PR: #270 ) is better. If others prefer this proposed way, though, I wouldn't block it

I think that's better because the original solution wasn't wrong, and students can see both ways to solve Fibonacci, but i'm going to wait for a final response to see what i should do!

**Comment by Luislev** [comment]
@thatblindgeye I've already commented out my solution as an alternative way to solve the challenge, can you take a look and see if everything is correct?

**Review by thatblindgeye — APPROVED** [review]

**Pull request merged**
