### PR TITLE
09_palindromes: Add test for strings with numbers

### PR DESCRIPTION
**Pull request by mariustelcean96**
Proposed by @thatblindgeye.

## Because

Strings with numbers inside of them can also be palindromes. This last test checks such strings.

## This PR

- The file _palindromes.spec.js_ now includes a 7th test.

## Issue

Closes #237 (I think. I might be wrong though)

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01_helloWorld: Update test cases`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If this PR includes changes that needs to be updated on the `solutions` branch, I have created another PR (and linked it to this PR).

### CODE REVIEW

**Review by rlmoser99 — CHANGES_REQUESTED** [review]
Thanks for making this addition, however we do not want the tests between this file and the one in the solutions folder to get out of sync. Would you be willing to also add this to the tests in `09_palindromes/solution/palindromes-solution.spec.js`?

**Comment by mariustelcean96** [comment]
Hi,

I would love to help this community grow and help others expand their knowledge.

However, I still don't understand some key concepts such as push, pull
requests, sync, merging requests, making modifications to a
repository, etc.

I will, hopefully, come back to your request once I am more familiar
with key concepts.

Marius Telcean

2023-03-18 23:51 GMT+02:00, Rachel Moser ***@***.***>:

**Comment by rlmoser99** [comment]
@mariustelcean96 I totally understand that learning git workflows can be overwhelming.

If you are open to practicing, follow these contributing instructions, using the `javascript-exercise` repo instead of the `curriculum` repo.
https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md#setting-up-your-local-clone

Make this same change to both test files, so that both files are changed at the same time. Then mention this PR when you create a new one, so we know to close this one when we merge in the new one.

You are also welcome to ask questions about this process in our Discord server, but if this still feel overwhelming and you'd rather pass, just let me know.

**Comment by mariustelcean96** [comment]
Hi Rachel,

I would love to keep practicing. However, this is a very busy period for
me. I will come back to this email once I have enough free time so learn.

The Odin Project is an amazing team work. It helped me land a job as a MES
Engineer.

Hope to hear from you soon.

Marius Telcean

În dum., 26 mar. 2023 la 23:50, Rachel Moser ***@***.***> a
scris:

**Review by thatblindgeye — APPROVED** [review]
Thanks for making this update @mariustelcean96 ! We're going to merge this in now and do a followup for the solutions file.

**Pull request merged**
