### PR TITLE
09_palindromes: Modify RegExp character class.

### PR DESCRIPTION
**Pull request by mariustelcean96**
The current code excludes digits/numbers from numeric strings, but they can also be palindromes.

The proposed change will match any word character that is not a word character from the basic Latin alphabet.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet#character_classes

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01_helloWorld: Update test cases`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have ensured any exercise files included in this PR have passed all of their tests

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

### CODE REVIEW

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
Can you confirm that all of the tests for this exercise still pass? Additionally, it might be worth adding a test for "works with numbers in a string".

**Comment by mariustelcean96** [comment]
Hi,

Thank you for taking the time to answer.

1. Confirmation that all of the test still pass with the proposed modification
screensh-palind-wout-addit-test

2. Regarding the additional test: "works with numbers in a string", I wrote a test. 
screensh-palind-with-addit-test

I am not sure how to add the additional code for the test at this step of the process.

**Review by thatblindgeye — COMMENTED** [review]
Thanks for the screenshot! Would you mind creating a followup issue to add a test for this exercise for strings with numbers?

The only other thing is there are some merge conflicts that need to be resolved.

**Comment by mariustelcean96** [comment]
Hello,

Thank you too for your reply. I `think` I created the [followup issue](https://github.com/TheOdinProject/javascript-exercises/pull/320) you were talking about. 

These things (pull requests, forks, issues, followups etc.) are still a bit out of my understanding area.

I added the test and resolved the merge conflict you mentioned.

**Comment by mariustelcean96** [comment]
Hi Eric,

I will try to do what you said during the weekend. I am on vacation right
now.

Marius

Le lun. 20 févr. 2023 à 15:57, Eric Olkowski ***@***.***> a
écrit :

**Comment by mariustelcean96** [comment]
> One last update: we just changes the solutions so that rather than a separate branch, each exercise has a solution directory in it. Could you update things so that the PR is against the main branch and the update is made inside the exercise solution directory?

I didn't know how to do the change so I [googled](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request) the terms. 

After I did that, Github showed me that there are 37 (or so) merge conflicts that need to be solved. I wanted to commit only to the 09:palindromes exercise alone. 

Once I pressed the **Sync fork** button, it removed any modifications I did to my fork. 

I will try again to implement the 'numbers in a string' test once I better understand this whole process.

**Pull request closed without merging**
