### PR TITLE
Readme.md: fix spelling

### PR DESCRIPTION
**Pull request by Alex-Nemet**
## Because

Found a minor spelling error while reading the lesson and wanted to help fix it. I also wanted to try contributing to my first open sourced project. 

## This PR

- changed spelling error of exercises 

## Issue

Closes #XXXXX

I don't think this is applicable

## Additional Information

n/a
## Pull Request Requirements

-   [x ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01_helloWorld: Update test cases`
-   [ x] The `Because` section summarizes the reason for this PR
-   [ x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x ] If this PR includes changes that needs to be updated on the `solutions` branch, I have created another PR (and linked it to this PR).

### CODE REVIEW

**Comment by Alex-Nemet** [comment]
I'm obviously new to this, tried to read how to do it all and help out. Sorry if I made any errors, was quite a lot to go through to correct a spelling error :)

**Review by thatblindgeye — DISMISSED** [review]
Thanks for making the update!

**Review by thatblindgeye — COMMENTED** [review]
Would you want to try resolving the merge conflicts for this PR? Since this is your first contribution you may not have had to handle those before, so no worries if you aren't comfortable with it yet

**Comment by Alex-Nemet** [comment]
I don't mind fixing the conflict, but I've never done it before. Looks like someone else made a change to the same area of the document that I did? They seemed to have added some clarification at the end of the paragraph. But did not fix the spelling mistake I tried to fix. So should I delete my portion of the merge and fix the spelling mistake in their paragraph? Not sure how to choose either one, should it be done in my code editor or can it just be done on github? Don't mean to create more work for you by explaining this to me.

**Comment by thatblindgeye** [comment]
@Alex-Nemet If you can see a "Resolve conflicts" button below (just above the comment textarea), you can use GitHub to resolve it.

Basically you'll want to keep the most up to date content, then make your update as part of resolving the conflict.

**Comment by Alex-Nemet** [comment]
I think I resolved the conflict, and tried to merge but it won't allow me to. I guess that gets passed on to you. Thanks for the help

**Review by thatblindgeye — APPROVED** [review]
Looks good! Thanks for resolving those conflicts 💪🏼

**Pull request merged**
