### PR TITLE
update the strings in repeatString.spec.js

### PR DESCRIPTION
**Pull request by ghost-2362003**
## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01_helloWorld: Update test cases`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If this PR includes changes that needs to be updated on the `solutions` branch, I have created another PR (and linked it to this PR).

### CODE REVIEW

**Comment by ghost-2362003** [comment]
Pls need review for merging

**Comment by ghost-2362003** [comment]
the strings in the repeatString.spec.js file were only hey

**Comment by CouchofTomato** [comment]
You need to link the issue this was discussed in. The template has a section where you can do it.

**Comment by xandora** [comment]
Closing this as the minimum required information is not in the form. Ticking all the boxes without reading any of them is also not a great look.

**Pull request closed without merging**
